name: 'auto-pull-request'
description: 'Updates a file according to provided template and creates pull request for this change'
inputs:
  repository:
    description: 'destination repo'
    required: true
  branch:
    description: 'destination branch'
    required: true
  file_path:
    description: 'file to create/change'
    required: true
  file_template:
    description: 'file content'
    required: true
  message:
    description: 'pull request message'
    required: true
  labels:
    description: 'pull request labels'
    required: false
    default: ''
  reviewers:
    description: 'pull request reviewers'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://sunx2ych/github-action-auto-pull-request:1.0.0'
